#!/bin/bash

lxc-stop krb
lxc-destroy krb
ssh-keygen -R "192.168.122.100"

lxc-stop nfs
lxc-destroy nfs
ssh-keygen -R "192.168.122.110"

lxc-stop ldap
lxc-destroy ldap
ssh-keygen -R "192.168.122.120"
