#!/bin/bash
set -e

ROOT_PASS=root
KRB5_PASS=krb5
KRB5_ADMIN_PASS=pass
USER_PASS=tommie

scripts/debian_roll kerberos
lxc-attach -n kerberos -v DEBIAN_FRONTEND=noninteractive -- apt-get -y install krb5-admin-server

scp configs/kerberos/krb5.conf root@192.168.122.100:/etc/
scp configs/kerberos/kdc.conf root@192.168.122.100:/etc/krb5kdc/
scp configs/kerberos/kadm5.acl root@192.168.122.100:/etc/krb5kdc/

lxc-attach -n kerberos -- bash -c 'echo -e "'$KRB5_PASS'\n'$KRB5_PASS'" | krb5_newrealm'
lxc-attach -n kerberos -- bash -c 'echo -e "'$KRB5_ADMIN_PASS'\n'$KRB5_ADMIN_PASS'" | kadmin.local addprinc root/admin'

lxc-attach -n kerberos -- systemctl restart krb5-admin-server
lxc-attach -n kerberos -- systemctl restart krb5-kdc

lxc-attach --clear-env -n kerberos -- bash -c 'echo -e "'$KRB5_ADMIN_PASS'\n'$USER_PASS'\n'$USER_PASS'\n" | kadmin addprinc tom'
